---
title: "git_00"
author: "Jayline Zelaya"
date: "Fall 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves

  Did gyre and gimble in the wabe:
      
All mimsy were the borogoves,

  And the mome raths outgrabe.
      

“Beware the Jabberwock, my son!


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,

And sorry I could not travel both

And be one traveler, long I stood

And looked down one as far as I could

To where it bent in the undergrowth;



## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,

  Shining with all his might:
  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

In numbers' dance, a tale unfolds,

A saga told in graphs and molds,

Statistical whispers, patterns keen,

A language deciphered, seldom seen.



Mean and median, the central guide,

Through spreadsheets vast, they gracefully glide,

Deviation hints at outliers afar,

In the realm of data, they bear a scar.



Histograms rise, bar by bar,

Revealing stories, both near and far,

Standard deviation measures the spread,

In a universe of numbers, where dreams are bred.



Regression lines plot a path so clear,

Predicting futures, allay our fear,

A realm of inference, where insights gleam,

In the realm of numbers, we dare to dream.



